# need to cd into api_duckdb dir to work
name: api_duckdb

services:
  api:
    image: plumber_db
    working_dir: /app
    ports:
      - "20619:8000"
    volumes:
      - ${PWD}/result:/app/result
      - ${PWD}/api.R:/app/api.R
    command: api.R
